# Independently sourced EEG: physical stimulus prediction

**Partial validation, not proof of great pain accuracy.** The feature-source cohorts are excluded. Ten independently sampled participants in OSF f2mua provide usable heat trials at **42/46/48°C**. Four-fold participant-held-out scores measure generalization to people, **not** independent cross-dataset transfer.

The second downloaded cohort (OSF w25k4) ends about 100 ms after shock; the planned poststimulus features cannot be recovered. It is excluded, not silently converted into a successful blind dataset. A pre-score availability amendment records this limitation.

Stimulus temperature is **not reported pain intensity**. These results cannot establish clinical pain prediction, causality or usefulness of every published feature estimator.

In [1]:
from pathlib import Path
import sys, json
import pandas as pd
from IPython.display import display, Markdown, Code
NOTEBOOK_DIR = Path.cwd()
sys.path.insert(0, str(NOTEBOOK_DIR))
__file__ = str(NOTEBOOK_DIR / 'evaluate.py')
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 20)
assert (NOTEBOOK_DIR / 'features.npz').exists(), 'Extract/download EEG first: see README.md'
display(pd.read_csv('dataset_eligibility.csv'))

,dataset,source,status,observed_target,reason
0,heat_f2mua,https://osf.io/f2mua/,eligible for participant-held-out scoring,42/46/48 Celsius via author codebook,Independent of feature-cited original cohorts;...
1,shock_w25k4,https://osf.io/w25k4/,downloaded but excluded,delivered/omitted fixed shock; no mA,Cue epochs end at +3.498 seconds; shocks occur...
2,cued_4kgtp,https://osf.io/4kgtp/,access blocked,Paper describes calibrated electrical stimulat...,Anonymous public API and article-published vie...
3,spinal_ds005307,https://openneuro.org/datasets/ds005307,physical dose mapping not verified,Examined event table has pain label and consta...,No trial-resolved laser energy mapping in exam...
4,nine_LEP_archives,https://doi.org/10.1038/s41597-025-05900-1,excluded feature-source cohorts,laser stimulation and pain ratings,All9 archives in the feature-cited678 particip...
5,chronic_pain_sources,https://osf.io/m45j2/,excluded and wrong target,resting chronic pain recordings,Feature-source/overlapping chronic cohorts exc...
6,DEIPP_ds006815,https://openneuro.org/datasets/ds006815,ineligible,spontaneous pain,MRI rather than usable scalp EEG with controll...

## Frozen design and target provenance

No model selection uses held-out performance. Source condition codes—not EEG correlations or subjective ratings—supply the target. Heat source MATLAB column 4 contains **cue codes**, not temperature. Temperature comes from the author's condition-combination codebook. Zero, 42, 46 and 48 are never introduced as fabricated observations.

In [2]:
display(Markdown('```json\n' + Path('protocol_availability_amendment.json').read_text() + '\n```'))
display(Markdown('```json\n' + Path('target_mapping.json').read_text() + '\n```'))
display(pd.read_csv('participant_target_counts.csv'))

```json
{
  "amendment_before_any_model_scores": true,
  "reason": "Raw schema/timing inspection, not predictive performance. The second deposited cohort is cue-epoched and ends at cue+3.498 s; collision/shock occurs around cue+3.36 to3.41 s. Only about0.09-0.14 s postshock remains. The prespecified0.05-1.25 s poststimulus feature window cannot be extracted. Some collision markers are outside the deposit entirely.",
  "do_not_do": ["Do not shorten windows to claim the same families were tested", "Do not relabel anticipation as a poststimulus pain response", "Do not reuse any excluded feature-source cohort", "Do not invent cross-dataset scores"],
  "available_stage": "Run the already prespecified four-fold participant-held-out classification and native temperature regression on heat_f2mua. These are genuine out-of-participant scores in a new cohort, NOT independent cross-dataset transfer.",
  "family_ablation_amendment": "Report fixed logistic family ablations over the same participant-held-out heat folds as exploratory. No feature selection, tuning or claim of independent validation of the resulting ranking.",
  "permutation_amendment": "Twenty within-training-participant label permutations, retaining each participant-held-out fold. Conditional exploratory null for the available cohort only.",
  "cross_dataset_stage": "BLOCKED pending a second independent pain EEG cohort with physical dose labels and adequate poststimulus recordings.",
  "great_accuracy_criterion": "Original two-cohort criterion remains unmet/untestable even if a single-cohort score is high. Do not apply it to fewer cohorts.",
  "scope": "This is a partial empirical result, not complete multi-dataset validation."
}

```

```json
{
  "heat": {
    "mapping_authority": "https://api.osf.io/v2/wikis/xc3vs/content/",
    "column": "trialinfo[:,1] (MATLAB column 2), stimulus-cue combination",
    "heat_conditions": "1-9 and 19-27",
    "temperature_mapping": "1-3,19-21 =42 C; 4-6,22-24 =46 C; 7-9,25-27 =48 C",
    "actual_schema": "Six columns; old wiki mentions four. Column 4 contains cue markers 37-42, NOT physical temperature. No rating column is used.",
    "alignment": "Deposited time vector around stimulus trigger; no intensity-dependent ramp-up shift.",
    "units_caveat": "MAT has no channel-unit field; voltage values treated as microvolts in line with BrainAmp export convention. This assumption affects amplitude QC and is explicitly disclosed."
  },
  "shock": {
    "mapping_authority": "https://raw.githubusercontent.com/dhewitt16/PainAnticipationVRStudy/main/EEGAnalysis/PPS_2_EpochFiles.m",
    "column": "epoch.eventtype / epoch.eventlatency",
    "positive": "PCollShock1-4: pain-related collision resulting in electrical shock",
    "negative": "PCollNoShock1-4: same pain-associated cues, omitted shock",
    "excluded": "middle/nonpain-associated cues and nPCollNoShock events",
    "alignment": "Collision-event latency in both delivered and omitted cases; not cue onset.",
    "source_processing": "Author average reference, 1-70 Hz filtering, 48-52 Hz stop filter, ICA/manual cleaning; already epoched. Not an equivalent raw preprocessing replication."
  }
}
```

       dataset                    subject  binary_target  trials
0   heat_f2mua   heat_f2mua:RawData_PART1              0      84
1   heat_f2mua   heat_f2mua:RawData_PART1              1     168
2   heat_f2mua  heat_f2mua:RawData_PART11              0      84
3   heat_f2mua  heat_f2mua:RawData_PART11              1     168
4   heat_f2mua  heat_f2mua:RawData_PART14              0      84
5   heat_f2mua  heat_f2mua:RawData_PART14              1     168
6   heat_f2mua  heat_f2mua:RawData_PART21              0      84
7   heat_f2mua  heat_f2mua:RawData_PART21              1     168
8   heat_f2mua  heat_f2mua:RawData_PART22              0      84
9   heat_f2mua  heat_f2mua:RawData_PART22              1     168
10  heat_f2mua  heat_f2mua:RawData_PART24              0      84
11  heat_f2mua  heat_f2mua:RawData_PART24              1     168
12  heat_f2mua   heat_f2mua:RawData_PART3              0      84
13  heat_f2mua   heat_f2mua:RawData_PART3              1     168
14  heat_f2mua  heat_f2mua:RawData_PART30              0      84
15  heat_f2mua  heat_f2mua:RawData_PART30              1     168
16  heat_f2mua  heat_f2mua:RawData_PART31              0      84
17  heat_f2mua  heat_f2mua:RawData_PART31              1     168
18  heat_f2mua   heat_f2mua:RawData_PART8              0      84
19  heat_f2mua   heat_f2mua:RawData_PART8              1     168

## Feature implementations and extraction code

The cache has 505 numeric EEG columns. Two supervised CSP columns are generated only inside training folds, giving 507 predictors for the full candidate model. Twenty-one of 23 families have candidate implementations. High gamma and CVUE/Piqβ are **not tested**, not approximated under their original names. FOOOF separates periodic peaks from the aperiodic component; an absent alpha peak remains missing.

Short-window PAF, connectivity, entropy and coupling estimates are exploratory. Fixed component-like extrema are not replicated WF+MLRd. Causal common filtering and fixed trigger interpolation use no target labels. Heat voltage units assume the BrainAmp microvolt convention because the deposited MAT lacks a unit field.

In [3]:
display(pd.read_csv('feature_family_coverage.csv')[['feature', 'generated_columns', 'status', 'implementation_note']])
display(pd.read_csv('generated_feature_catalogue.csv').head(20))
print('Full column catalogue is generated_feature_catalogue.csv')

,feature,generated_columns,status,implementation_note
0,Evoked N1/N2/P2 amplitudes,9,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
1,Evoked latencies/morphology,27,candidate implementation tested; not an exact ...,Prespecified extrema/latencies and six mean wa...
2,Alpha/beta ERD,6,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
3,High-gamma response,0,not tested,Common 1-40 Hz pipeline; source shock EEG was ...
4,Pre-stimulus power/phase,36,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
5,Absolute/relative spectral power,60,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
6,Peak alpha frequency,4,candidate implementation tested; not an exact ...,"FOOOF 1.1.1, fixed aperiodic mode; central PSD..."
7,Aperiodic slope/offset,4,candidate implementation tested; not an exact ...,"FOOOF 1.1.1, fixed aperiodic mode; central PSD..."
8,Hemispheric power asymmetry,30,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
9,Alpha/theta power ratio,6,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
10,Magnitude-squared coherence,32,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
11,PLV/phase synchrony,32,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
12,PLI/wPLI/imaginary coherency,96,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
13,Phase–amplitude coupling,12,candidate implementation tested; not an exact ...,Tort 18-bin MI: theta-beta and alpha-30-40 Hz....
14,Envelope correlation,32,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
15,CVUE/Piqβ,0,not tested,No valid reproduction of source-specific long-...
16,Within-window amplitude variability,54,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
17,Higuchi fractal dimension,6,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
18,Permutation entropy,12,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
19,Sample/multiscale entropy,12,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
20,Hjorth parameters,18,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...
21,CSP/spatial log-variance,2,trained inside each training fold only,Two generalized-eigenvector log-variance featu...
22,Signal quality/SNR and variance controls,17,candidate implementation tested; not an exact ...,Fixed common montage and short event epochs; e...

,feature,family_code,family,finite_trials,missing_trials,total_trials
0,contrast__erd__central_alpha,erd,Alpha/beta ERD,2520,0,2520
1,contrast__erd__central_beta,erd,Alpha/beta ERD,2520,0,2520
2,contrast__erd__frontal_alpha,erd,Alpha/beta ERD,2520,0,2520
3,contrast__erd__frontal_beta,erd,Alpha/beta ERD,2520,0,2520
4,contrast__erd__posterior_alpha,erd,Alpha/beta ERD,2520,0,2520
5,contrast__erd__posterior_beta,erd,Alpha/beta ERD,2520,0,2520
6,contrast__quality__central_peak_baseline_sd_ratio,quality,Signal quality/SNR and variance controls,2520,0,2520
7,contrast__quality__frontal_peak_baseline_sd_ratio,quality,Signal quality/SNR and variance controls,2520,0,2520
8,contrast__quality__posterior_peak_baseline_sd_...,quality,Signal quality/SNR and variance controls,2520,0,2520
9,post__aper__central_exponent,aper,Aperiodic slope/offset,2520,0,2520
10,post__aper__central_offset,aper,Aperiodic slope/offset,2520,0,2520
11,post__asym__C3_C4_alpha,asym,Hemispheric power asymmetry,2520,0,2520
12,post__asym__C3_C4_beta,asym,Hemispheric power asymmetry,2520,0,2520
13,post__asym__C3_C4_delta,asym,Hemispheric power asymmetry,2520,0,2520
14,post__asym__C3_C4_lowgamma,asym,Hemispheric power asymmetry,2520,0,2520
15,post__asym__C3_C4_theta,asym,Hemispheric power asymmetry,2520,0,2520
16,post__asym__F3_F4_alpha,asym,Hemispheric power asymmetry,2520,0,2520
17,post__asym__F3_F4_beta,asym,Hemispheric power asymmetry,2520,0,2520
18,post__asym__F3_F4_delta,asym,Hemispheric power asymmetry,2520,0,2520
19,post__asym__F3_F4_lowgamma,asym,Hemispheric power asymmetry,2520,0,2520

Full column catalogue is generated_feature_catalogue.csv

In [4]:
for filename in ['readers.py', 'features.py', 'build_features.py']:
    display(Markdown('### ' + filename))
    display(Code(filename=filename, language='python'))

### readers.py

"""Explicit target mappings from author documentation, not EEG/label correlations."""
import json
import re
from pathlib import Path

import numpy as np
from scipy.io import loadmat
from scipy.signal import butter, resample_poly, sosfilt

HERE = Path(__file__).resolve().parent
WORKSPACE = HERE.parent.parent
CHANNELS = ["F3", "F4", "Fz", "C3", "C4", "Cz", "P3", "P4", "Pz"]


def channels(labels):
    lookup = {str(v).strip().upper(): i for i, v in enumerate(labels)}
    missing = [c for c in CHANNELS if c.upper() not in lookup]
    if missing:
        raise ValueError(f"Missing prespecified channels: {missing}")
    return [lookup[c.upper()] for c in CHANNELS]


def prepare(x, time, fs, onset=0.0):
    """Causal filter: our prestimulus features cannot use future samples.

    Deposited shock EEG has prior author zero-phase processing, which cannot
    be undone. Thus its prestimulus control is not a clean causal negative control.
    """
    x = np.asarray(x, float)
    time = np.asarray(time, float) - onset
    if not np.isfinite(x).all():
        return None, "nonfinite"
    x -= x.mean(axis=0, keepdims=True)
    # Same masking for delivered and omitted stimuli and both modalities.
    # Suppress immediate trigger/current artifacts; do not choose by target label.
    mask = (time >= -0.010) & (time <= 0.030)
    if mask.any():
        for row in x:
            row[mask] = np.interp(time[mask], time[~mask], row[~mask])
    x = sosfilt(butter(4, [1, 40], btype="bandpass", fs=fs, output="sos"), x, axis=-1)
    if fs != 500:
        raise ValueError(f"Unreviewed sampling rate {fs}; no silent resampling assumptions")
    x = resample_poly(x, 1, 2, axis=-1)
    time = time[::2][:x.shape[-1]]
    pre_mask = (time >= -0.8) & (time < -0.05)
    post_mask = (time >= 0.05) & (time < 1.25)
    if pre_mask.sum() < 185 or post_mask.sum() < 298:
        return None, "incomplete_window"
    pre, post = x[:, pre_mask], x[:, post_mask]
    if np.max(np.abs(post)) > 400 or np.max(np.abs(pre)) > 200:
        return None, "amplitude_threshold"
    if np.median(np.std(post, axis=1)) < 0.05:
        return None, "flat_signal"
    # Epoch-only centering uses no target labels, fitted cohort statistics or metadata.
    baseline = pre.mean(axis=1, keepdims=True)
    return (pre - baseline, post - baseline), None


def heat(path):
    d = loadmat(path, simplify_cells=True)["data"]
    info = np.asarray(d["trialinfo"])
    if info.ndim != 2 or info.shape[1] != 6:
        raise ValueError("Expected deposited six-column trialinfo; wiki's old four-column description is not used")
    idx = channels(d["label"])
    fs = float(d["fsample"])
    for i, code in enumerate(info[:, 1].astype(int)):
        # Author OSF wiki: 1-9 = pain cue / heat, 19-27 = picture cue / heat.
        # Within each group three cue intensities cycle inside each physical heat level.
        # DO NOT use column 4 (codes 37-42): it describes cues, not actual stimulus.
        if not (1 <= code <= 9 or 19 <= code <= 27):
            continue
        local = code if code <= 9 else code - 18
        temperature = [42.0, 46.0, 48.0][(local - 1) // 3]
        windows, error = prepare(np.asarray(d["trial"][i])[idx].copy(),
                                 d["time"][i], fs)
        yield {"source_trial": i, "temperature_c": temperature,
               "binary_target": int(temperature >= 46), "target_native": temperature,
               "target_units": "degrees Celsius", "condition_code": code,
               "block_context": None, "windows": windows, "error": error}


def as_list(value):
    if isinstance(value, (list, tuple, np.ndarray)):
        return list(np.asarray(value, dtype=object).reshape(-1))
    return [value]


def shock(path):
    d = loadmat(path, simplify_cells=True)
    idx = channels([c["labels"] for c in d["chanlocs"]])
    fs = float(d["srate"])
    time = np.asarray(d["times"], float) / 1000.0
    epochs = as_list(d["epoch"])
    for i, epoch in enumerate(epochs):
        types = [str(v) for v in as_list(epoch["eventtype"])]
        latencies = [float(v) / 1000 for v in as_list(epoch["eventlatency"])]
        if len(types) != len(latencies):
            raise ValueError("Unmatched event type / latency")
        # Restrict to the same pain-associated cue population.
        current_cues = [v for v, t in zip(types, latencies)
                        if abs(t) < 0.003 and re.fullmatch(r"(left|right)[1-4]", v)]
        if len(current_cues) != 1:
            continue
        events = [(v, t) for v, t in zip(types, latencies)
                  if re.fullmatch(r"PColl(Shock|NoShock)[1-4]", v) and 0 < t < 3.5]
        if len(events) != 1:
            yield {"source_trial": i, "windows": None, "error": "ambiguous_collision"}
            continue
        name, onset = events[0]
        target = int(name.startswith("PCollShock"))
        windows, error = prepare(np.asarray(d["data"])[idx, :, i].copy(), time, fs, onset)
        yield {"source_trial": i, "temperature_c": np.nan, "binary_target": target,
               "target_native": target, "target_units": "delivered/omitted fixed shock 0/1",
               "condition_code": name, "block_context": int(name[-1]),
               "windows": windows, "error": error}


def describe_targets():
    return {
        "heat": {
            "mapping_authority": "https://api.osf.io/v2/wikis/xc3vs/content/",
            "column": "trialinfo[:,1] (MATLAB column 2), stimulus-cue combination",
            "heat_conditions": "1-9 and 19-27",
            "temperature_mapping": "1-3,19-21 =42 C; 4-6,22-24 =46 C; 7-9,25-27 =48 C",
            "actual_schema": "Six columns; old wiki mentions four. Column 4 contains cue markers 37-42, NOT physical temperature. No rating column is used.",
            "alignment": "Deposited time vector around stimulus trigger; no intensity-dependent ramp-up shift.",
            "units_caveat": "MAT has no channel-unit field; voltage values treated as microvolts in line with BrainAmp export convention. This assumption affects amplitude QC and is explicitly disclosed."
        },
        "shock": {
            "mapping_authority": "https://raw.githubusercontent.com/dhewitt16/PainAnticipationVRStudy/main/EEGAnalysis/PPS_2_EpochFiles.m",
            "column": "epoch.eventtype / epoch.eventlatency",
            "positive": "PCollShock1-4: pain-related collision resulting in electrical shock",
            "negative": "PCollNoShock1-4: same pain-associated cues, omitted shock",
            "excluded": "middle/nonpain-associated cues and nPCollNoShock events",
            "alignment": "Collision-event latency in both delivered and omitted cases; not cue onset.",
            "source_processing": "Author average reference, 1-70 Hz filtering, 48-52 Hz stop filter, ICA/manual cleaning; already epoched. Not an equivalent raw preprocessing replication."
        }
    }

### features.py

"""Candidate feature-family implementations; no labels enter this module."""
import json
import math
import warnings
from pathlib import Path

import numpy as np
from scipy import signal, stats
from sklearn.neighbors import KDTree

with warnings.catch_warnings():
    warnings.simplefilter("ignore", DeprecationWarning)
    from fooof import FOOOF

FS = 250
ROI = {"frontal": [0, 1, 2], "central": [3, 4, 5], "posterior": [6, 7, 8]}
BANDS = {"delta": (1, 4), "theta": (4, 8), "alpha": (8, 13),
         "beta": (13, 30), "lowgamma": (30, 40)}
PAIRS = {"F3_F4": (0, 1), "C3_C4": (3, 4), "Fz_Cz": (2, 5), "Cz_Pz": (5, 8)}
FAMILIES = {
    "erp": "Evoked N1/N2/P2 amplitudes",
    "morph": "Evoked latencies/morphology",
    "erd": "Alpha/beta ERD",
    "pre": "Pre-stimulus power/phase",
    "power": "Absolute/relative spectral power",
    "paf": "Peak alpha frequency",
    "aper": "Aperiodic slope/offset",
    "asym": "Hemispheric power asymmetry",
    "ratio": "Alpha/theta power ratio",
    "coh": "Magnitude-squared coherence",
    "plv": "PLV/phase synchrony",
    "lag": "PLI/wPLI/imaginary coherency",
    "pac": "Phase–amplitude coupling",
    "env": "Envelope correlation",
    "variability": "Within-window amplitude variability",
    "hfd": "Higuchi fractal dimension",
    "pe": "Permutation entropy",
    "sampen": "Sample/multiscale entropy",
    "hjorth": "Hjorth parameters",
    "quality": "Signal quality/SNR and variance controls",
    "csp": "CSP/spatial log-variance",
}


def permutation_entropy(x, order=3):
    a = np.lib.stride_tricks.sliding_window_view(x, order)
    ranks = np.argsort(a, axis=1, kind="stable")
    _, count = np.unique(ranks, axis=0, return_counts=True)
    p = count / count.sum()
    return float(-np.sum(p * np.log(p)) / np.log(math.factorial(order)))


def higuchi(x, kmax=8):
    n = len(x)
    lengths = []
    for k in range(1, kmax + 1):
        values = []
        for m in range(k):
            seq = x[m::k]
            count = len(seq) - 1
            values.append(np.sum(np.abs(np.diff(seq))) * (n - 1) /
                          (max(count, 1) * k * k))
        lengths.append(np.mean(values))
    return float(np.polyfit(np.log(1 / np.arange(1, kmax + 1)),
                            np.log(np.maximum(lengths, 1e-15)), 1)[0])


def sample_entropy(x, scale=1):
    if scale > 1:
        n = len(x) // scale
        x = x[:n * scale].reshape(n, scale).mean(axis=1)
    sd = np.std(x)
    if sd < 1e-12 or len(x) < 12:
        return np.nan
    patterns = np.lib.stride_tricks.sliding_window_view(x, 3)
    radius = 0.2 * sd
    counts = []
    for dimensions in (2, 3):
        a = np.ascontiguousarray(patterns[:, :dimensions])
        matches = KDTree(a, metric="chebyshev").query_radius(a, radius, count_only=True) - 1
        counts.append(matches.sum())
    return float(-np.log(counts[1] / counts[0])) if min(counts) > 0 else np.nan


def modulation_index(phase, amplitude):
    bins = np.clip(((phase + np.pi) * 18 / (2 * np.pi)).astype(int), 0, 17)
    values = np.array([amplitude[bins == i].mean() if np.any(bins == i) else 0
                       for i in range(18)])
    p = np.maximum(values, 1e-15)
    p /= p.sum()
    return float((np.log(18) + np.sum(p * np.log(p))) / np.log(18))


def single_window(x, prefix):
    out = {}

    def put(family, name, value):
        out[f"{prefix}__{family}__{name}"] = float(value)

    f, p = signal.welch(x, FS, nperseg=min(250, x.shape[-1]),
                        noverlap=0, axis=-1)
    band_power = {}
    total = np.trapezoid(p[:, (f >= 1) & (f <= 40)], f[(f >= 1) & (f <= 40)], axis=-1)
    for name, (low, high) in BANDS.items():
        keep = (f >= low) & (f <= high)
        bp = np.trapezoid(p[:, keep], f[keep], axis=-1)
        band_power[name] = bp
        for roi, idx in ROI.items():
            put("power", f"{roi}_{name}_logabs", np.log10(np.mean(bp[idx]) + 1e-12))
            put("power", f"{roi}_{name}_relative", np.mean(bp[idx] / (total[idx] + 1e-12)))
    for roi, idx in ROI.items():
        put("ratio", roi, np.log((np.mean(band_power["alpha"][idx]) + 1e-12) /
                                (np.mean(band_power["theta"][idx]) + 1e-12)))
        a = x[idx].mean(axis=0)
        sd = np.std(a)
        d1, d2 = np.diff(a), np.diff(a, n=2)
        mobility = np.std(d1) / max(sd, 1e-12)
        put("hjorth", f"{roi}_activity", np.var(a))
        put("hjorth", f"{roi}_mobility", mobility)
        put("hjorth", f"{roi}_complexity",
            (np.std(d2) / max(np.std(d1), 1e-12)) / max(mobility, 1e-12))
        put("hfd", roi, higuchi(a))
        for order in (3, 5):
            put("pe", f"{roi}_order{order}", permutation_entropy(a, order))
        for scale in (1, 2):
            put("sampen", f"{roi}_scale{scale}", sample_entropy(a, scale))
        for name, value in {
                "sd": sd, "ptp": np.ptp(a), "skew": stats.skew(a), "kurtosis": stats.kurtosis(a),
                "subwindow_sd_cv": np.std([np.std(v) for v in np.array_split(a, 3)]) /
                                   max(np.mean([np.std(v) for v in np.array_split(a, 3)]), 1e-12)
        }.items():
            put("variability", f"{roi}_{name}", value)
    for name in BANDS:
        for pair, (a, b) in {"F3_F4": (0, 1), "C3_C4": (3, 4), "P3_P4": (6, 7)}.items():
            put("asym", f"{pair}_{name}",
                np.log((band_power[name][a] + 1e-12) / (band_power[name][b] + 1e-12)))
    # FOOOF: fit periodic peaks separately, unlike a raw log-log linear slope.
    central_psd = p[ROI["central"]].mean(axis=0)
    fm = FOOOF(peak_width_limits=(3, 12), max_n_peaks=3, min_peak_height=0.1,
               peak_threshold=2.0, aperiodic_mode="fixed", verbose=False)
    fm.fit(f, np.maximum(central_psd, 1e-15), [2, 40])
    if fm.has_model:
        put("aper", "central_offset", fm.aperiodic_params_[0])
        put("aper", "central_exponent", fm.aperiodic_params_[1])
        peaks = fm.peak_params_
        eligible = peaks[(peaks[:, 0] >= 8) & (peaks[:, 0] <= 13)]
        peak = eligible[np.argmax(eligible[:, 1])] if len(eligible) else [np.nan] * 3
        put("paf", "central_peak_hz", peak[0])
        put("paf", "central_peak_height", peak[1])
        put("quality", "spectral_fit_r2", fm.r_squared_)
    else:
        for family, name in [("aper", "central_offset"), ("aper", "central_exponent"),
                             ("paf", "central_peak_hz"), ("paf", "central_peak_height"),
                             ("quality", "spectral_fit_r2")]:
            put(family, name, np.nan)
    analytic = {}
    for name in ("theta", "alpha", "beta", "lowgamma"):
        low, high = BANDS[name]
        filtered = signal.sosfiltfilt(
            signal.butter(3, [low, high], btype="bandpass", fs=FS, output="sos"), x, axis=-1)
        z = signal.hilbert(filtered, axis=-1)
        analytic[name] = z
        for roi, idx in ROI.items():
            amp = np.abs(z[idx])
            put("variability", f"{roi}_{name}_envelope_cv",
                np.mean(np.std(amp, axis=-1) / np.maximum(np.mean(amp, axis=-1), 1e-12)))
        for pair, (a, b) in PAIRS.items():
            phase_difference = np.angle(z[a]) - np.angle(z[b])
            imaginary = np.imag(z[a] * np.conjugate(z[b]))
            put("plv", f"{pair}_{name}", np.abs(np.mean(np.exp(1j * phase_difference))))
            put("lag", f"{pair}_{name}_pli", abs(np.mean(np.sign(np.sin(phase_difference)))))
            put("lag", f"{pair}_{name}_wpli",
                abs(np.mean(imaginary)) / max(np.mean(abs(imaginary)), 1e-12))
            put("env", f"{pair}_{name}", np.corrcoef(np.abs(z[a]), np.abs(z[b]))[0, 1])
            fw, pxy = signal.csd(x[a], x[b], FS, nperseg=125, noverlap=62)
            _, pxx = signal.welch(x[a], FS, nperseg=125, noverlap=62)
            _, pyy = signal.welch(x[b], FS, nperseg=125, noverlap=62)
            keep = (fw >= low) & (fw <= high)
            coherency = pxy / np.sqrt(np.maximum(pxx * pyy, 1e-24))
            put("coh", f"{pair}_{name}", np.mean(np.abs(coherency[keep]) ** 2))
            put("lag", f"{pair}_{name}_imaginary_coherency",
                np.mean(np.abs(np.imag(coherency[keep]))))
        if prefix == "pre":
            for roi, idx in ROI.items():
                zmean = z[idx].mean(axis=0)
                put("pre", f"{roi}_{name}_end_phase_sin", np.sin(np.angle(zmean[-1])))
                put("pre", f"{roi}_{name}_end_phase_cos", np.cos(np.angle(zmean[-1])))
                put("pre", f"{roi}_{name}_power", np.mean(band_power[name][idx]))
    for phase_name, amp_name in [("theta", "beta"), ("alpha", "lowgamma")]:
        for roi, idx in ROI.items():
            phase = np.angle(analytic[phase_name][idx].mean(axis=0))
            amplitude = np.abs(analytic[amp_name][idx]).mean(axis=0)
            put("pac", f"{roi}_{phase_name}_{amp_name}", modulation_index(phase, amplitude))
    for roi, idx in ROI.items():
        a = x[idx].mean(axis=0)
        put("quality", f"{roi}_log_total_power", np.log10(np.mean(total[idx]) + 1e-12))
        put("quality", f"{roi}_line_length", np.mean(np.abs(np.diff(a))))
    return out, band_power


def extract(pre, post):
    before, pre_power = single_window(pre, "pre")
    after, post_power = single_window(post, "post")
    out = {**before, **after}
    for roi, idx in ROI.items():
        for band in ("alpha", "beta"):
            out[f"contrast__erd__{roi}_{band}"] = (
                np.mean(post_power[band][idx]) - np.mean(pre_power[band][idx])) / (
                    np.mean(pre_power[band][idx]) + 1e-12)
        a = post[idx].mean(axis=0)
        pre_noise = np.std(pre[idx].mean(axis=0))
        time = 0.05 + np.arange(len(a)) / FS
        for component, (start, end, direction) in {
                "N1_like": (0.08, 0.18, -1), "N2_like": (0.18, 0.40, -1),
                "P2_like": (0.40, 0.75, 1)}.items():
            keep = (time >= start) & (time <= end)
            b = a[keep]
            loc = np.argmax(b * direction)
            out[f"post__erp__{roi}_{component}_amplitude_uv"] = b[loc]
            out[f"post__morph__{roi}_{component}_latency_s"] = time[keep][loc]
        for j, values in enumerate(np.array_split(a, 6)):
            out[f"post__morph__{roi}_bin{j}_mean_uv"] = values.mean()
        out[f"contrast__quality__{roi}_peak_baseline_sd_ratio"] = np.max(abs(a)) / max(pre_noise, 1e-12)
    central = post[ROI["central"]]
    covariance = np.cov(central)
    return out, covariance.astype(np.float32)


def family(name):
    return name.split("__")[1]


def feature_set(names, which, omit=None):
    if which == "power_only":
        mask = np.array([family(n) == "power" for n in names])
    elif which == "prestimulus_only":
        mask = np.array([n.startswith("pre__") for n in names])
    else:
        mask = np.ones(len(names), bool)
    if omit:
        mask &= np.array([family(n) != omit for n in names])
    return mask

### build_features.py

"""Extract the frozen candidates from downloaded real EEG."""
import collections
import csv
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd

from features import FAMILIES, extract
from readers import WORKSPACE, describe_targets, heat, shock

HERE = Path(__file__).resolve().parent


def main():
    metadata, vectors, covariance = [], [], []
    names = None
    audit = []
    manifest = json.loads((HERE / "download_manifest.json").read_text())
    (HERE / "target_mapping.json").write_text(json.dumps(describe_targets(), indent=2))
    for r in manifest:
        if r["status"] != "downloaded":
            audit.append({**r, "exclusion": "download_failed"})
            continue
        reader = heat if r["dataset"].startswith("heat") else shock
        subject = Path(r["name"]).stem
        errors = collections.Counter()
        included = 0
        try:
            for row in reader(WORKSPACE / r["path"]):
                if row["error"]:
                    errors[row["error"]] += 1
                    continue
                feats, cov = extract(*row.pop("windows"))
                if names is None:
                    names = sorted(feats)
                if set(feats) != set(names):
                    raise ValueError("Feature schema changed across trials")
                row.pop("error")
                metadata.append({**row, "dataset": r["dataset"], "subject": f"{r['dataset']}:{subject}"})
                vectors.append([feats[n] for n in names])
                covariance.append(cov)
                included += 1
        except Exception as e:
            # A schema/algorithm error is fatal, not a silently dropped cohort.
            audit.append({"dataset": r["dataset"], "subject": subject, "fatal_error": repr(e)})
            (HERE / "extraction_audit.json").write_text(json.dumps(audit, indent=2))
            raise
        audit.append({"dataset": r["dataset"], "subject": subject, "included_trials": included,
                      "quality_exclusions": dict(errors), "sha256": r["sha256"]})
        print(r["dataset"], subject, "included", included, "excluded", dict(errors), flush=True)
        (HERE / "extraction_audit.json").write_text(json.dumps(audit, indent=2))
    if not vectors:
        raise ValueError("No usable independently labeled EEG trials; no fabricated scores")
    matrix = np.asarray(vectors, float)
    matrix[~np.isfinite(matrix)] = np.nan
    np.savez_compressed(HERE / "features.npz", X=matrix, names=np.array(names),
                        covariance=np.stack(covariance))
    frame = pd.DataFrame(metadata)
    frame.to_csv(HERE / "trial_metadata.csv", index=False)
    finish_reports(frame, matrix, names)


def finish_reports(frame, matrix, names):
    counts = frame.groupby(["dataset", "subject", "binary_target"]).size().rename("trials").reset_index()
    counts.to_csv(HERE / "participant_target_counts.csv", index=False)
    generated = pd.DataFrame({
        "feature": names, "family_code": [n.split("__")[1] for n in names],
        "family": [FAMILIES[n.split("__")[1]] for n in names],
        "finite_trials": np.isfinite(matrix).sum(axis=0),
        "missing_trials": np.isnan(matrix).sum(axis=0),
        "total_trials": len(frame)
    })
    generated.to_csv(HERE / "generated_feature_catalogue.csv", index=False)
    original = pd.read_csv(HERE.parent / "feature_prediction_table.csv")
    coverage = []
    for _, row in original.iterrows():
        values = row.to_dict()
        family_name = values["feature"]
        family_code = next((k for k, v in FAMILIES.items() if v == family_name), None)
        number = int((generated.family == family_name).sum())
        status = "candidate implementation tested; not an exact paper-specific algorithm replication"
        note = "Fixed common montage and short event epochs; exploratory family-level validation."
        if family_name == "High-gamma response":
            status, note = "not tested", "Common 1-40 Hz pipeline; source shock EEG was already filtered at 70 Hz. No 60-100 Hz substitute."
        elif family_name == "CVUE/Piqβ":
            status, note = "not tested", "No valid reproduction of source-specific long-record Piqβ estimator/threshold from short epochs. Envelope CV is labelled variability instead."
        elif family_code == "csp":
            number, status, note = 2, "trained inside each training fold only", "Two generalized-eigenvector log-variance features; training low/higher labels, not PCA."
        elif family_code in ("paf", "aper"):
            note = "FOOOF 1.1.1, fixed aperiodic mode; central PSD 2-40 Hz, alpha component 8-13 Hz. Missing peaks remain NaN, not forced estimates. Short windows limit spectral precision."
        elif family_code == "morph":
            note = "Prespecified extrema/latencies and six mean waveform bins; NOT Hu WF+MLRd."
        elif family_code == "pac":
            note = "Tort 18-bin MI: theta-beta and alpha-30-40 Hz. Very few cycles per epoch; not a significance-tested coupling claim."
        coverage.append({**values, "status": status, "generated_columns": number, "implementation_note": note})
    pd.DataFrame(coverage).to_csv(HERE / "feature_family_coverage.csv", index=False)
    summary = {
        "trials": len(frame), "columns_cached": len(names), "csp_columns_inside_training": 2,
        "participants": frame.groupby("dataset").subject.nunique().to_dict(),
        "trials_by_dataset": frame.groupby("dataset").size().to_dict(),
        "finite_fraction": float(np.isfinite(matrix).mean()),
        "families_tested": len({n.split('__')[1] for n in names}) + 1,
        "untested_families": ["High-gamma response", "CVUE/Piqβ"],
        "scope": "No dimensionality reduction/PCA or unsupervised clustering altered; new supervised validation only."
    }
    (HERE / "feature_summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()

## Actual fitted-model code

The cells below contain the executable source of evaluate.py. Imputation, scaling and CSP see training subjects only. There is no PCA, clustering, threshold tuning or feature selection on held-out scores. Dummy, fixed linear and fixed Extra Trees models are all reported; none is declared best to fit the desired outcome.

In [5]:
"""Frozen models, true cohort holdouts, participant splits and negative controls."""
import hashlib
import json
import platform
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import scipy
import sklearn
from scipy.linalg import eigh
from sklearn.dummy import DummyClassifier, DummyRegressor
from sklearn.ensemble import ExtraTreesClassifier, ExtraTreesRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, f1_score,
                             mean_absolute_error, mean_squared_error, r2_score, roc_auc_score)
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from features import FAMILIES, feature_set

HERE = Path(__file__).resolve().parent
SEED = 20261009

/home/runner/workspace/eeg-variance-pain-literature/blind_stimulus_validation/features.py:13: DeprecationWarning:
The `fooof` package is being deprecated and replaced by the `specparam` (spectral parameterization) package.
This version of `fooof` (1.1) is fully functional, but will not be further updated.
New projects are recommended to update to using `specparam` (see Changelog for details).
  from fooof import FOOOF

### `model`

In [6]:
def model(kind, task):
    if task == "regression":
        estimator = {
            "dummy": lambda: DummyRegressor(strategy="mean"),
            "ridge": lambda: Ridge(alpha=10),
            "extra_trees": lambda: ExtraTreesRegressor(
                n_estimators=200, max_depth=8, min_samples_leaf=8,
                max_features=0.7, random_state=SEED, n_jobs=2)
        }[kind]()
    else:
        estimator = {
            "dummy": lambda: DummyClassifier(strategy="most_frequent"),
            "logistic": lambda: LogisticRegression(
                C=0.1, class_weight="balanced", max_iter=3000, random_state=SEED),
            "extra_trees": lambda: ExtraTreesClassifier(
                n_estimators=200, max_depth=8, min_samples_leaf=8,
                max_features=0.7, class_weight="balanced", random_state=SEED, n_jobs=2)
        }[kind]()
    return make_pipeline(SimpleImputer(strategy="median", keep_empty_features=True),
                         StandardScaler(), estimator)

### `csp`

In [7]:
def csp(train_cov, test_cov, binary_y):
    """Equivalent two-filter CSP, using only TRAINING class covariance means."""
    train = train_cov / np.maximum(np.trace(train_cov, axis1=1, axis2=2)[:, None, None], 1e-12)
    test = test_cov / np.maximum(np.trace(test_cov, axis1=1, axis2=2)[:, None, None], 1e-12)
    if len(np.unique(binary_y)) < 2:
        raise ValueError("CSP needs both training stimulus classes")
    a, b = train[binary_y == 0].mean(axis=0), train[binary_y == 1].mean(axis=0)
    eye = np.eye(3) / 3
    a, b = 0.9 * a + 0.1 * eye, 0.9 * b + 0.1 * eye
    _, vectors = eigh(a, a + b)
    weights = vectors[:, [0, -1]]

    def transform(cov):
        variance = np.einsum("ai,nab,bi->ni", weights, cov, weights)
        return np.log(np.maximum(variance, 1e-12))

    return transform(train), transform(test)

### `matrices`

In [8]:
def matrices(X, covariance, names, train_idx, test_idx, which, binary_y, omit=None):
    mask = feature_set(names, which, omit)
    train, test = X[train_idx][:, mask], X[test_idx][:, mask]
    if which == "all_compatible" and omit != "csp":
        a, b = csp(covariance[train_idx], covariance[test_idx], binary_y)
        train, test = np.column_stack([train, a]), np.column_stack([test, b])
    return train, test

### `scores`

In [9]:
def scores(y, prediction, task, probability=None):
    if task == "regression":
        levels = np.array([42., 46., 48.])
        rounded = levels[np.argmin(np.abs(prediction[:, None] - levels), axis=1)]
        return {
            "R2": r2_score(y, prediction), "MAE": mean_absolute_error(y, prediction),
            "RMSE": np.sqrt(mean_squared_error(y, prediction)),
            "native_level_accuracy": accuracy_score(y, rounded),
            "native_level_balanced_accuracy": balanced_accuracy_score(y, rounded)
        }
    return {
        "accuracy": accuracy_score(y, prediction),
        "balanced_accuracy": balanced_accuracy_score(y, prediction),
        "ROC_AUC": roc_auc_score(y, probability) if len(np.unique(y)) == 2 else np.nan,
        "macro_F1": f1_score(y, prediction, average="macro", zero_division=0)
    }

### `bootstrap`

In [10]:
def bootstrap(frame, task):
    rng = np.random.default_rng(SEED)
    groups = frame.subject.unique()
    indices = {s: np.flatnonzero(frame.subject.to_numpy() == s) for s in groups}
    y = frame.true_target.to_numpy()
    p = frame.prediction.to_numpy()
    prob = frame.probability.to_numpy()
    collected = {}
    for _ in range(1000):
        idx = np.concatenate([indices[s] for s in rng.choice(groups, len(groups), replace=True)])
        # All chosen subjects should have both classes; disclose any undefined replicate.
        if task != "regression" and len(np.unique(y[idx])) < 2:
            continue
        values = scores(y[idx], p[idx], task, prob[idx])
        for k, v in values.items():
            if np.isfinite(v):
                collected.setdefault(k, []).append(v)
    return {f"{k}_CI_{tail}": float(np.quantile(v, q))
            for k, v in collected.items() for tail, q in [("low", 0.025), ("high", 0.975)]}

### `prediction_rows`

In [11]:
def prediction_rows(meta, test_idx, estimator, test, task, tags, fold):
    y = meta.target_native.to_numpy() if task == "regression" else meta.binary_target.to_numpy()
    prediction = estimator.predict(test)
    prob = (estimator.predict_proba(test)[:, 1] if task != "regression"
            else np.full(len(test_idx), np.nan))
    return pd.DataFrame({
        **tags, "fold": fold, "subject": meta.subject.to_numpy()[test_idx],
        "source_trial": meta.source_trial.to_numpy()[test_idx],
        "true_target": y[test_idx], "prediction": prediction, "probability": prob
    })

### `freeze_code`

In [12]:
def freeze_code():
    files = ["protocol.json", "protocol_availability_amendment.json", "acquire.py", "readers.py", "features.py",
             "build_features.py", "evaluate.py"]
    digests = {n: hashlib.sha256((HERE / n).read_bytes()).hexdigest() for n in files}
    path = HERE / "analysis_frozen.json"
    if path.exists():
        before = json.loads(path.read_text())
        assert before["file_sha256"] == digests, "Analysis changed after predictive evaluation freeze"
    else:
        path.write_text(json.dumps({
            "UTC_before_first_model_fit": datetime.now(timezone.utc).isoformat(),
            "file_sha256": digests,
            "implementation_detail": "Fourth-order causal 1-40 Hz filter, fixed -10..+30 ms trigger interpolation for every class, resample 500 to250Hz; source shock filtering remains irreversible.",
            "native_level_accuracy_definition": "Regressor predictions rounded to nearest prespecified 42/46/48 C; no threshold optimized on data.",
            "retrospective": True,
            "not_public_preregistration": True
        }, indent=2))

### `main`

In [13]:
def main():
    freeze_code()
    data = np.load(HERE / "features.npz")
    X, covariance, names = data["X"], data["covariance"], data["names"]
    meta = pd.read_csv(HERE / "trial_metadata.csv")
    if len(meta) != len(X):
        raise ValueError("Features / target rows not aligned")
    for dataset, part in meta.groupby("dataset"):
        if part.subject.nunique() < 8 or part.binary_target.nunique() != 2:
            raise ValueError(f"Insufficient usable participants/classes in {dataset}")
    y_binary = meta.binary_target.to_numpy()
    datasets = sorted(meta.dataset.unique())
    feature_sets = ["power_only", "all_compatible", "prestimulus_only"]
    predictions = []
    split_audit = []

    def run(train_idx, test_idx, evaluation, train_key, test_key, task, fold):
        train_subjects = set(meta.subject.iloc[train_idx])
        test_subjects = set(meta.subject.iloc[test_idx])
        assert not train_subjects.intersection(test_subjects), "Participant leakage"
        if evaluation == "cross_dataset":
            assert set(meta.dataset.iloc[train_idx]).isdisjoint(set(meta.dataset.iloc[test_idx]))
        split_audit.append({
            "evaluation": evaluation, "train_dataset": train_key, "test_dataset": test_key,
            "fold": fold, "task": task, "train_subjects": sorted(train_subjects),
            "test_subjects": sorted(test_subjects), "subject_overlap": [],
            "training_rows": len(train_idx), "testing_rows": len(test_idx)
        })
        target = meta.target_native.to_numpy() if task == "regression" else y_binary
        kinds = ["dummy", "ridge", "extra_trees"] if task == "regression" else ["dummy", "logistic", "extra_trees"]
        for which in feature_sets:
            train, test = matrices(X, covariance, names, train_idx, test_idx,
                                   which, y_binary[train_idx])
            for kind in kinds:
                estimator = model(kind, task).fit(train, target[train_idx])
                tags = {"evaluation": evaluation, "train_dataset": train_key,
                        "test_dataset": test_key, "task": task, "feature_set": which,
                        "model": kind, "units": "degrees Celsius" if task == "regression" else "source-defined low/higher contrast 0/1"}
                predictions.append(prediction_rows(meta, test_idx, estimator, test, task, tags, fold))
        print(evaluation, train_key, "->", test_key, task, "fold", fold, flush=True)

    if len(datasets) >= 2:
        for heldout in datasets:
            test_idx = np.flatnonzero(meta.dataset.to_numpy() == heldout)
            train_idx = np.flatnonzero(meta.dataset.to_numpy() != heldout)
            run(train_idx, test_idx, "cross_dataset", next(d for d in datasets if d != heldout),
                heldout, "classification", 0)
    else:
        print("CROSS-DATASET VALIDATION BLOCKED: only one eligible independently sourced cohort. No transfer scores produced.", flush=True)
    for dataset in datasets:
        idx = np.flatnonzero(meta.dataset.to_numpy() == dataset)
        part = meta.iloc[idx]
        for fold, (train, test) in enumerate(GroupKFold(n_splits=4).split(
                np.zeros(len(idx)), groups=part.subject.to_numpy())):
            run(idx[train], idx[test], "subject_heldout", dataset, dataset, "classification", fold)
            if dataset.startswith("heat"):
                run(idx[train], idx[test], "subject_heldout", dataset, dataset, "regression", fold)
    all_predictions = pd.concat(predictions, ignore_index=True)
    all_predictions.to_csv(HERE / "heldout_predictions.csv", index=False)
    (HERE / "split_leakage_audit.json").write_text(json.dumps(split_audit, indent=2))
    keys = ["evaluation", "train_dataset", "test_dataset", "task", "feature_set", "model", "units"]
    results, participant_results = [], []
    for values, part in all_predictions.groupby(keys):
        tags = dict(zip(keys, values))
        task = tags["task"]
        measured = scores(part.true_target.to_numpy(), part.prediction.to_numpy(), task,
                          part.probability.to_numpy())
        results.append({**tags, "test_subjects": part.subject.nunique(), "test_trials": len(part),
                        **measured, **bootstrap(part, task)})
        for subject, sp in part.groupby("subject"):
            participant_results.append({**tags, "subject": subject, "test_trials": len(sp),
                                        **scores(sp.true_target.to_numpy(), sp.prediction.to_numpy(),
                                                 task, sp.probability.to_numpy())})
    result_frame = pd.DataFrame(results)
    result_frame.to_csv(HERE / "accuracy_results.csv", index=False)
    pd.DataFrame(participant_results).to_csv(HERE / "participant_accuracy_results.csv", index=False)
    print("Measured holdout scores and clustered intervals saved", flush=True)
    gain_rows = []
    gain_evaluation = "cross_dataset" if len(datasets) >= 2 else "subject_heldout"
    cross = all_predictions[(all_predictions.evaluation == gain_evaluation) &
                            (all_predictions.model == "logistic")]
    for heldout in datasets:
        full = cross[(cross.test_dataset == heldout) &
                     (cross.feature_set == "all_compatible")].sort_values(["subject", "source_trial"])
        power = cross[(cross.test_dataset == heldout) &
                      (cross.feature_set == "power_only")].sort_values(["subject", "source_trial"])
        assert full[["subject", "source_trial"]].to_numpy().tolist() == power[["subject", "source_trial"]].to_numpy().tolist()
        full, power = full.reset_index(drop=True), power.reset_index(drop=True)
        groups = full.subject.unique()
        lookup = {s: np.flatnonzero(full.subject.to_numpy() == s) for s in groups}
        y, fp, pp = full.true_target.to_numpy(), full.prediction.to_numpy(), power.prediction.to_numpy()
        gains, rng = [], np.random.default_rng(SEED)
        for _ in range(1000):
            ix = np.concatenate([lookup[s] for s in rng.choice(groups, len(groups), replace=True)])
            gains.append(balanced_accuracy_score(y[ix], fp[ix]) - balanced_accuracy_score(y[ix], pp[ix]))
        gain_rows.append({"evaluation": gain_evaluation, "test_dataset": heldout,
                          "balanced_accuracy_gain_full_minus_power": balanced_accuracy_score(y, fp) - balanced_accuracy_score(y, pp),
                          "gain_CI_low": np.quantile(gains, .025), "gain_CI_high": np.quantile(gains, .975)})
    pd.DataFrame(gain_rows).to_csv(HERE / "feature_set_gains.csv", index=False)

    # Prespecified family ablations, no selection/tuning on the resulting scores.
    ablations, nulls = [], []
    for heldout in datasets:
        if len(datasets) >= 2:
            folds = [(np.flatnonzero(meta.dataset.to_numpy() != heldout),
                      np.flatnonzero(meta.dataset.to_numpy() == heldout))]
        else:
            indices = np.flatnonzero(meta.dataset.to_numpy() == heldout)
            folds = [(indices[a], indices[b]) for a, b in GroupKFold(n_splits=4).split(
                indices, groups=meta.subject.to_numpy()[indices])]
        observed = cross[(cross.test_dataset == heldout) & (cross.feature_set == "all_compatible")]
        observed_score = balanced_accuracy_score(observed.true_target, observed.prediction)
        for omit, label in FAMILIES.items():
            truths, predictions_removed = [], []
            for train_idx, test_idx in folds:
                a, b = matrices(X, covariance, names, train_idx, test_idx,
                                "all_compatible", y_binary[train_idx], omit=omit)
                estimator = model("logistic", "classification").fit(a, y_binary[train_idx])
                truths.extend(y_binary[test_idx])
                predictions_removed.extend(estimator.predict(b))
            removed_score = balanced_accuracy_score(truths, predictions_removed)
            ablations.append({"evaluation": gain_evaluation, "test_dataset": heldout, "removed_family": label,
                              "balanced_accuracy_without_family": removed_score,
                              "balanced_accuracy_full": observed_score,
                              "full_minus_without_family": observed_score - removed_score,
                              "interpretation": "Positive = family helps at this holdout; exploratory, correlated families, no independent selection validation"})
        rng = np.random.default_rng(SEED)
        for replicate in range(20):
            truths, predictions_permuted = [], []
            for train_idx, test_idx in folds:
                groups = meta.subject.to_numpy()[train_idx]
                permuted = y_binary[train_idx].copy()
                for subject in np.unique(groups):
                    local = np.flatnonzero(groups == subject)
                    permuted[local] = rng.permutation(permuted[local])
                a, b = matrices(X, covariance, names, train_idx, test_idx,
                                "all_compatible", permuted)
                estimator = model("logistic", "classification").fit(a, permuted)
                truths.extend(y_binary[test_idx])
                predictions_permuted.extend(estimator.predict(b))
            value = balanced_accuracy_score(truths, predictions_permuted)
            nulls.append({"evaluation": gain_evaluation, "test_dataset": heldout, "permutation": replicate,
                          "permuted_balanced_accuracy": value, "observed_balanced_accuracy": observed_score})
        print("Family ablations and 20 label permutations:", heldout, flush=True)
    pd.DataFrame(ablations).to_csv(HERE / "family_ablation_results.csv", index=False)
    null_frame = pd.DataFrame(nulls)
    null_frame.to_csv(HERE / "permutation_controls.csv", index=False)
    null_summary = []
    for heldout, part in null_frame.groupby("test_dataset"):
        null_summary.append({"test_dataset": heldout, "permutations": len(part),
                             "observed_balanced_accuracy": part.observed_balanced_accuracy.iloc[0],
                             "mean_permuted_balanced_accuracy": part.permuted_balanced_accuracy.mean(),
                             "empirical_one_sided_p": (1 + (part.permuted_balanced_accuracy >= part.observed_balanced_accuracy).sum()) / (1 + len(part)),
                             "limitation": "20 permutations: smallest attainable p=1/21; exploratory, not familywise-corrected"})
    pd.DataFrame(null_summary).to_csv(HERE / "permutation_summary.csv", index=False)
    primary = result_frame[(result_frame.evaluation == "cross_dataset") &
                           (result_frame.feature_set == "all_compatible") &
                           (result_frame.model == "logistic")]
    great = bool(len(primary) >= 2 and (primary.balanced_accuracy >= .8).all() and
                 (primary.balanced_accuracy_CI_low > .5).all() and
                 all(r["balanced_accuracy_gain_full_minus_power"] > 0 for r in gain_rows))
    gain_supported = bool(len(datasets) >= 2 and all(r["gain_CI_low"] > 0 for r in gain_rows))
    verdict = {
        "predeclared_great_contrast_accuracy_met": great,
        "all_features_improve_over_power_with_positive_lower_CI_on_both_cohorts": gain_supported,
        "clinical_pain_prediction_validated": False,
        "absolute_cross_modal_physical_intensity_validated": False,
        "summary": ("Operational low/higher stimulus contrast threshold met; not clinical pain validation."
                    if great else "Great cross-dataset accuracy is NOT validated. Only one cohort had usable dose-labeled poststimulus EEG; the independent second-cohort stage is blocked."),
        "cohorts_with_measured_scores": len(datasets), "sampling": "10 presampled participants per cohort; usable counts in feature_summary.json",
        "interpretation": "Heat = measured Celsius, shock = presence of a fixed dose. Cross-cohort transfer scores apply only to the source-defined contrast. No mA or pain ratings were inferred.",
        "uncertainty": "Participant-cluster intervals conditional on each fitted training model; only two cohorts, retrospective holdouts, source-preprocessing and modality differences.",
        "software": {"python": platform.python_version(), "numpy": np.__version__,
                     "scipy": scipy.__version__, "sklearn": sklearn.__version__, "fooof": "1.1.1"}
    }
    (HERE / "verdict.json").write_text(json.dumps(verdict, indent=2))
    print(json.dumps(verdict, indent=2), flush=True)

## Execute the prespecified empirical test

This cell performs real fits on cached features extracted from the downloaded EEG. It also produces 1000 participant-cluster bootstrap intervals, 21 family ablations and 20 grouped training-label permutation controls. The cache is included in the bundle; raw EEG is downloaded separately rather than redistributed.

In [14]:
main()

CROSS-DATASET VALIDATION BLOCKED: only one eligible independently sourced cohort. No transfer scores produced.

subject_heldout heat_f2mua -> heat_f2mua classification fold 0

subject_heldout heat_f2mua -> heat_f2mua regression fold 0

subject_heldout heat_f2mua -> heat_f2mua classification fold 1

subject_heldout heat_f2mua -> heat_f2mua regression fold 1

subject_heldout heat_f2mua -> heat_f2mua classification fold 2

subject_heldout heat_f2mua -> heat_f2mua regression fold 2

subject_heldout heat_f2mua -> heat_f2mua classification fold 3

subject_heldout heat_f2mua -> heat_f2mua regression fold 3

Measured holdout scores and clustered intervals saved

Family ablations and 20 label permutations: heat_f2mua

{
  "predeclared_great_contrast_accuracy_met": false,
  "all_features_improve_over_power_with_positive_lower_CI_on_both_cohorts": false,
  "clinical_pain_prediction_validated": false,
  "absolute_cross_modal_physical_intensity_validated": false,
  "summary": "Great cross-dataset accuracy is NOT validated. Only one cohort had usable dose-labeled poststimulus EEG; the independent second-cohort stage is blocked.",
  "cohorts_with_measured_scores": 1,
  "sampling": "10 presampled participants per cohort; usable counts in feature_summary.json",
  "interpretation": "Heat = measured Celsius, shock = presence of a fixed dose. Cross-cohort transfer scores apply only to the source-defined contrast. No mA or pain ratings were inferred.",
  "uncertainty": "Participant-cluster intervals conditional on each fitted training model; only two cohorts, retrospective holdouts, source-preprocessing and modality differences.",
  "software": {
    "python": "3.13.11",
    "numpy": "2.5.3",
    "scipy": "1.18.1",
    "sklearn": "1.9.1",
    "fooof": "1.1.1"
  }
}

## Held-out temperature prediction, in native degrees Celsius

**R², MAE and RMSE are the continuous-prediction metrics.** Exact-level accuracy rounds a regressor's prediction to the nearest protocol-defined 42/46/48°C, without using test labels to choose cutoffs.

In [15]:
results = pd.read_csv('accuracy_results.csv')
display(results[results.task == 'regression'][['evaluation','feature_set','model','test_subjects','test_trials','R2','R2_CI_low','R2_CI_high','MAE','RMSE','native_level_accuracy']])

,evaluation,feature_set,model,test_subjects,test_trials,R2,R2_CI_low,R2_CI_high,MAE,RMSE,native_level_accuracy
9,subject_heldout,all_compatible,dummy,10,2520,0.000000,0.000000,0.000000,2.222222,2.494438,0.333333
10,subject_heldout,all_compatible,extra_trees,10,2520,-0.006954,-0.018923,0.000657,2.237376,2.503096,0.333333
11,subject_heldout,all_compatible,ridge,10,2520,-1.358922,-3.473713,-0.271948,2.918495,3.831154,0.343651
12,subject_heldout,power_only,dummy,10,2520,0.000000,0.000000,0.000000,2.222222,2.494438,0.333333
13,subject_heldout,power_only,extra_trees,10,2520,-0.021306,-0.033595,-0.013202,2.231391,2.520871,0.333333
14,subject_heldout,power_only,ridge,10,2520,-0.040707,-0.071676,-0.018031,2.231997,2.544702,0.333333
15,subject_heldout,prestimulus_only,dummy,10,2520,0.000000,0.000000,0.000000,2.222222,2.494438,0.333333
16,subject_heldout,prestimulus_only,extra_trees,10,2520,-0.004572,-0.010883,0.000952,2.227594,2.500134,0.333333
17,subject_heldout,prestimulus_only,ridge,10,2520,-0.471969,-1.075601,-0.111358,2.468918,3.026370,0.340476

## Secondary lower/higher-temperature classification

42°C versus 46/48°C is an experimental contrast, **not a validated pain diagnosis**. A majority predictor reaches 66.7% ordinary accuracy but only 50% balanced accuracy. Always compare with that baseline; chance ordinary accuracy is not 50% here.

In [16]:
display(results[results.task == 'classification'][['evaluation','feature_set','model','accuracy','balanced_accuracy','balanced_accuracy_CI_low','balanced_accuracy_CI_high','ROC_AUC','macro_F1']])
display(pd.read_csv('feature_set_gains.csv'))

,evaluation,feature_set,model,accuracy,balanced_accuracy,balanced_accuracy_CI_low,balanced_accuracy_CI_high,ROC_AUC,macro_F1
0,subject_heldout,all_compatible,dummy,0.666667,0.500000,0.500000,0.500000,0.500000,0.400000
1,subject_heldout,all_compatible,extra_trees,0.623810,0.507738,0.498512,0.517560,0.514863,0.486243
2,subject_heldout,all_compatible,logistic,0.511111,0.513690,0.494345,0.533036,0.516978,0.497684
3,subject_heldout,power_only,dummy,0.666667,0.500000,0.500000,0.500000,0.500000,0.400000
4,subject_heldout,power_only,extra_trees,0.565873,0.501190,0.490774,0.510722,0.495479,0.500773
5,subject_heldout,power_only,logistic,0.503571,0.502381,0.488683,0.516369,0.501228,0.488612
6,subject_heldout,prestimulus_only,dummy,0.666667,0.500000,0.500000,0.500000,0.500000,0.400000
7,subject_heldout,prestimulus_only,extra_trees,0.607143,0.500893,0.490774,0.510417,0.510101,0.485844
8,subject_heldout,prestimulus_only,logistic,0.521032,0.520833,0.508929,0.531845,0.524514,0.506041

,evaluation,test_dataset,balanced_accuracy_gain_full_minus_power,gain_CI_low,gain_CI_high
0,subject_heldout,heat_f2mua,0.01131,-0.008631,0.036905

## Candidate-family contribution and negative controls

A positive full-minus-without-family score means the family helped this fixed model in these folds; a negative value means removal helped. Correlated families and 21 comparisons prevent a causal or independently validated ranking. Do **not** select families here and call the resulting score a fresh blind test.

Only 20 permutations: the smallest possible empirical p-value is 1/21. These controls are exploratory. Bootstrap intervals resample whole participants but do not capture all uncertainty from retraining on a new cohort.

In [17]:
display(pd.read_csv('family_ablation_results.csv').sort_values('full_minus_without_family', ascending=False))
display(pd.read_csv('permutation_summary.csv'))
display(Markdown('```json\n' + Path('verdict.json').read_text() + '\n```'))

,evaluation,test_dataset,removed_family,balanced_accuracy_without_family,balanced_accuracy_full,full_minus_without_family,interpretation
15,subject_heldout,heat_f2mua,Higuchi fractal dimension,0.509821,0.51369,0.003869,Positive = family helps at this holdout; explo...
11,subject_heldout,heat_f2mua,PLI/wPLI/imaginary coherency,0.511310,0.51369,0.002381,Positive = family helps at this holdout; explo...
4,subject_heldout,heat_f2mua,Absolute/relative spectral power,0.512500,0.51369,0.001190,Positive = family helps at this holdout; explo...
17,subject_heldout,heat_f2mua,Sample/multiscale entropy,0.512798,0.51369,0.000893,Positive = family helps at this holdout; explo...
8,subject_heldout,heat_f2mua,Alpha/theta power ratio,0.513095,0.51369,0.000595,Positive = family helps at this holdout; explo...
16,subject_heldout,heat_f2mua,Permutation entropy,0.513988,0.51369,-0.000298,Positive = family helps at this holdout; explo...
2,subject_heldout,heat_f2mua,Alpha/beta ERD,0.514286,0.51369,-0.000595,Positive = family helps at this holdout; explo...
6,subject_heldout,heat_f2mua,Aperiodic slope/offset,0.515774,0.51369,-0.002083,Positive = family helps at this holdout; explo...
19,subject_heldout,heat_f2mua,Signal quality/SNR and variance controls,0.516071,0.51369,-0.002381,Positive = family helps at this holdout; explo...
0,subject_heldout,heat_f2mua,Evoked N1/N2/P2 amplitudes,0.516667,0.51369,-0.002976,Positive = family helps at this holdout; explo...
1,subject_heldout,heat_f2mua,Evoked latencies/morphology,0.516667,0.51369,-0.002976,Positive = family helps at this holdout; explo...
5,subject_heldout,heat_f2mua,Peak alpha frequency,0.516667,0.51369,-0.002976,Positive = family helps at this holdout; explo...
18,subject_heldout,heat_f2mua,Hjorth parameters,0.519048,0.51369,-0.005357,Positive = family helps at this holdout; explo...
20,subject_heldout,heat_f2mua,CSP/spatial log-variance,0.521131,0.51369,-0.007440,Positive = family helps at this holdout; explo...
9,subject_heldout,heat_f2mua,Magnitude-squared coherence,0.521429,0.51369,-0.007738,Positive = family helps at this holdout; explo...
13,subject_heldout,heat_f2mua,Envelope correlation,0.522917,0.51369,-0.009226,Positive = family helps at this holdout; explo...
12,subject_heldout,heat_f2mua,Phase–amplitude coupling,0.523214,0.51369,-0.009524,Positive = family helps at this holdout; explo...
10,subject_heldout,heat_f2mua,PLV/phase synchrony,0.523810,0.51369,-0.010119,Positive = family helps at this holdout; explo...
7,subject_heldout,heat_f2mua,Hemispheric power asymmetry,0.523810,0.51369,-0.010119,Positive = family helps at this holdout; explo...
14,subject_heldout,heat_f2mua,Within-window amplitude variability,0.526786,0.51369,-0.013095,Positive = family helps at this holdout; explo...
3,subject_heldout,heat_f2mua,Pre-stimulus power/phase,0.529167,0.51369,-0.015476,Positive = family helps at this holdout; explo...

,test_dataset,permutations,observed_balanced_accuracy,mean_permuted_balanced_accuracy,empirical_one_sided_p,limitation
0,heat_f2mua,20,0.51369,0.499435,0.095238,20 permutations: smallest attainable p=1/21; e...

```json
{
  "predeclared_great_contrast_accuracy_met": false,
  "all_features_improve_over_power_with_positive_lower_CI_on_both_cohorts": false,
  "clinical_pain_prediction_validated": false,
  "absolute_cross_modal_physical_intensity_validated": false,
  "summary": "Great cross-dataset accuracy is NOT validated. Only one cohort had usable dose-labeled poststimulus EEG; the independent second-cohort stage is blocked.",
  "cohorts_with_measured_scores": 1,
  "sampling": "10 presampled participants per cohort; usable counts in feature_summary.json",
  "interpretation": "Heat = measured Celsius, shock = presence of a fixed dose. Cross-cohort transfer scores apply only to the source-defined contrast. No mA or pain ratings were inferred.",
  "uncertainty": "Participant-cluster intervals conditional on each fitted training model; only two cohorts, retrospective holdouts, source-preprocessing and modality differences.",
  "software": {
    "python": "3.13.11",
    "numpy": "2.5.3",
    "scipy": "1.18.1",
    "sklearn": "1.9.1",
    "fooof": "1.1.1"
  }
}
```

## What remains blocked

No usable second independently graded pain EEG cohort has been scored. Thus no cross-dataset accuracy or universal physical-dose calibration is reported. The original two-cohort 'great accuracy' criterion cannot be satisfied by these single-cohort results. Missing subjective ratings were never filled in.

Reproduce acquisition/extraction with acquire.py and build_features.py. Original literature tables and earlier unsupervised analyses remain unchanged. See README.md for dependencies, the full file catalogue, provenance and instructions.